typography_spectrum: 0.14799224236048758
color:
  saturation: 0.744263221975416
  brandStrength: 0.6784731682855636
  lightness: 0.8891729698516428
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
  rhythmicContrast: 0.3010173465590924
layout_spectrum: 0.643613084917888
analytics:
  google: UA-82820124-1
author:
  name: Martin Hinteregger
  email: martin.hint@gmail.com
name: pictureplis
navigation:
  - name: Austria
    id: 8c473b56-b353-497e-b739-06cf7aa72d86
    type: content
  - name: travelblog
    url: www.pictureplis.com
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PICTUREPLIS
description: 'just pictures, nothing else'
